#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup

p = requests.get('https://fnbr.co')

soup = BeautifulSoup(p.text, 'html.parser')

heading = soup.find(lambda e: e.name == 'h2' and e.text == 'All Items')
all_items = heading.find_next_sibling()

titles = all_items.find_all('h4', {'class': 'card-title'})
prices = all_items.find_all('p', {'class': 'itemprice'})

for t in zip(titles, prices):
    print('Item: {}\nPrice: {}\n'.format(t[0].text.strip(), t[1].text.strip()))
